<a href="https://colab.research.google.com/github/rahiakela/deep-learning-for-nlp-by-jason-brownlee/blob/part-1-data-preparation/3_preparing_text_data_with_keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Preparing Text Data With Keras

You cannot feed raw text directly into deep learning models. Text data must be encoded as
numbers to be used as input or output for machine learning and deep learning models, such
as word embeddings. The Keras deep learning library provides some basic tools to help you
prepare your text data.

## Setup

In [0]:
from __future__ import absolute_import, division, print_function, unicode_literals

try:
  # %tensorflow_version only exists in Colab.
  %tensorflow_version 2.x
except Exception:
  pass

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.preprocessing.text import text_to_word_sequence, one_hot, hashing_trick, Tokenizer
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

## Split Words with text to word sequence

A good first step when working with text is to split it into words. Words are called tokens and the process of splitting text into tokens is called tokenization. Keras provides the
text to word sequence() function that you can use to split text into a list of words. 
By default, this function automatically does 3 things:

* Splits words by space.
* Filters out punctuation.
* Converts text to lowercase (lower=True).

In [2]:
# define the document
text = 'The quick brown fox jumped over the lazy dog.'

# tokenize the document
result = text_to_word_sequence(text)
print(result)

['the', 'quick', 'brown', 'fox', 'jumped', 'over', 'the', 'lazy', 'dog']


## Encoding with one hot

It is popular to represent a document as a sequence of integer values, where each word in the document is represented as a unique integer. Keras provides the one hot() function that you
can use to tokenize and integer encode a text document in one step. The name suggests that it will create a one hot encoding of the document, which is not the case. 

Instead, the function is a wrapper for the hashing trick() function. The function returns an integer encoded version of the document. The use of a hash function means that there may be collisions and not all words will be assigned unique integer values. As with the text to word sequence() function, the one hot() function will make the text lower case, filter out punctuation, and split words based on white space.

In addition to the text, the vocabulary size (total words) must be specified. This could be the total number of words in the document or more if you intend to encode additional documents
that contains additional words. The size of the vocabulary defines the hashing space from which words are hashed. By default, the hash function is used, alternate hash functions can be specified when calling the hashing trick() function directly.

We can use the text to word sequence() function to split the document into words and then use a set to represent only the unique words in the document. The size of this set can be used to estimate the size of the vocabulary for one document.

In [3]:
# estimate the size of the vocabulary
words = set(text_to_word_sequence(text))
vocab_size = len(words)
print(vocab_size)

8


We can put this together with the one hot() function and encode the words in the document. The vocabulary size is increased by one-third to minimize collisions when hashing words.

In [5]:
# integer encode the document
result = one_hot(text, round(vocab_size * 1.3))
print(result)

[3, 6, 6, 5, 9, 5, 3, 9, 4]


## Hash Encoding with hashing trick

A limitation of integer and count base encodings is that they must maintain a vocabulary of words and their mapping to integers. An alternative to this approach is to use a one-way hash function to convert words to integers. This avoids the need to keep track of a vocabulary, which is faster and requires less memory.

Keras provides the hashing trick() function that tokenizes and then integer encodes the document, just like the one hot() function. It provides more  exibility, allowing you to specify
the hash function as either hash (the default) or other hash functions such as the built in md5 function or your own function.

In [7]:
# integer encode the document
result = hashing_trick(text, round(vocab_size * 1.3), hash_function='md5')
print(result)

[6, 4, 1, 2, 7, 5, 6, 2, 6]


## Tokenizer API

So far we have looked at one-off convenience methods for preparing text with Keras. Keras provides a more sophisticated API for preparing text that can be fit and reused to prepare
multiple text documents. This may be the preferred approach for large projects. Keras provides the Tokenizer class for preparing text documents for deep learning. The Tokenizer must be constructed and then fit on either raw text documents or integer encoded text documents.

In [0]:
# define 5 documents
docs = [
  'Well done!',
  'Good work',
  'Great effort',
  'nice work',
  'Excellent!'
]

# create the tokenizer
t = Tokenizer()

# fit the tokenizer on the documents
t.fit_on_texts(docs)

Once fit, the Tokenizer provides 4 attributes that you can use to query what has been learned about your documents:
* **word_counts**: A dictionary of words and their counts.
* **word_docs**: An integer count of the total number of documents that were used to fit the Tokenizer.
* **word_index**: A dictionary of words and their uniquely assigned integers.
* **document_count**: A dictionary of words and how many documents each appeared in.


In [10]:
# summarize what was learned
print(t.word_counts)
print(t.word_docs)
print(t.word_index)
print(t.document_count)

OrderedDict([('well', 1), ('done', 1), ('good', 1), ('work', 2), ('great', 1), ('effort', 1), ('nice', 1), ('excellent', 1)])
defaultdict(<class 'int'>, {'well': 1, 'done': 1, 'good': 1, 'work': 2, 'great': 1, 'effort': 1, 'nice': 1, 'excellent': 1})
{'work': 1, 'well': 2, 'done': 3, 'good': 4, 'great': 5, 'effort': 6, 'nice': 7, 'excellent': 8}
5


Once the Tokenizer has been fit on training data, it can be used to encode documents in the train or test datasets. The texts to matrix() function on the Tokenizer can be used to
create one vector per document provided per input. The length of the vectors is the total size of the vocabulary. This function provides a suite of standard bag-of-words model text encoding schemes that can be provided via a mode argument to the function. The modes available include:

* **binary**: Whether or not each word is present in the document. This is the default.
* **count**: The count of each word in the document.
* **tfidf**: The Text Frequency-Inverse DocumentFrequency (TF-IDF) scoring for each word in the document.
* **freq**: The frequency of each word as a ratio of words within each document.

In [11]:
# integer encode documents
encoded_docs = t.texts_to_matrix(docs, mode='count')
print(encoded_docs)

[[0. 0. 1. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]
